### PR TITLE
setup.py: Add six to install_requires (fixes #24)

### LINKED ISSUE #24: [0.4.8] setup.{cfg,py} missing install_requires=['six'] ?
Hi!

I see use of six both in Python code as well as in `requirements.txt`. Is there a reason why `setup.{cfg,py}` does not mention six for a runtime dependency?

Thanks and best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #24

### CODE REVIEW

**Comment by ssbarnea** [comment]
@hartwork You will have to fix CI/CD first. Feel free to remove py34.

**Comment by ssbarnea** [comment]
Please make py34 removal in another PR, these two changes should not be in the same PR. Once py34 is removed, this one should be a one-liner.

I will make a new release once done, so you can use it.

**Comment by hartwork** [comment]
I missed the CI failure somehow, sorry. I have dropped Python 3.4 now.
It still fails [related to twine](https://travis-ci.com/github/pycontribs/wstools/jobs/319518288#L452). I see that twine is in `whitelist_externals`. Should it try adding twine at https://github.com/pycontribs/wstools/blob/master/.travis.yml#L14 or would you prefer some other approach?

**Comment by hartwork** [comment]
> Please make py34 removal in another PR, these two changes should not be in the same PR. Once py34 is removed, this one should be a one-liner.

Okay, no problem. before I start the py34 removal PR please let me know your thoughts on the twine thing mentioned above. Thanks!

**Comment by ssbarnea** [comment]
Add twine to https://github.com/pycontribs/wstools/blob/master/requirements-dev.txt and it shoul be fine.

**Comment by hartwork** [comment]
> Add twine to https://github.com/pycontribs/wstools/blob/master/requirements-dev.txt and it shoul be fine.

Okay. The twine fix will need to be part of the py34 removal PR to get the CI green, correct?

**Comment by ssbarnea** [comment]
@hartwork Do one PR named "Remove py34 and fix CI" and it should be fine, both are linked.

Remember to remove py34 classifier from setup.cfg

**Comment by ssbarnea** [comment]
Now you can rebase.

**Comment by hartwork** [comment]
Done, and the CI even likes it.

**Pull request merged**
